# Generated by Django 2.0.1 on 2018-01-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.CharField(default='', max_length=256, verbose_name='profile'),
        ),
    ]
