# Generated by Django 2.0.1 on 2018-01-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_auto_20180111_1407'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
    ]
